### PR TITLE
Numerous fixes and configuration options

### PR DESCRIPTION
**Pull request by ryan-lane**
This pull request changes the following:
1. Changes the skin file structure to make it a non-autoloaded skin, which allows the use of resource loader, configuration options, and makes enabling the skin slightly easier.
2. Adds resource loader support
3. Adds the responsive css by default
4. Fixes some bugs with contentSub and contentSub2
5. Adds configuration options for different layout styles
6. Removes a lot of unused code and commented out output
7. Changes the dropdown for page titles to be a static localized "Page" message to ensure layout doesn't break
8. Adds configuration option to always show navbar to anons
9. Adds "Show other languages" into the navbar
10. Adds configuration option to show sidebar as a set of dropdowns, rather than a list of items
11. Fixes all errors, notices and warnings shown in php error log

### CODE REVIEW

**Comment by waldyrious** [comment]
fixes #2

**Comment by ryan-lane** [comment]
Ok. That's the last of the commits. Sorry for such a giant pull request.

**Comment by garrett** [comment]
Thanks for all the fixes! 

I've been sick with the flu since returning from FOSDEM (past week and a half or so) and intend on reviewing and merging next week (when I'm hopefully feeling well again). Sorry for the delay.

**Comment by ryan-lane** [comment]
Anything you'd like me to change/remove/add?

**Comment by garrett** [comment]
Sorry for the delay; I'm finally caught up with work enough (after being sick for a few weeks) to look it all over and test everything out. It looks good to me, and I'm merging it all in!

Thanks again for your commits! Awesome work!

**Pull request merged**
